### ISSUE TITLE
Brainstorming on how to gather rules

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/plu-stan#6]

**Comment by bogdan-manole** [comment]
the meeting participants could be: Stephano, @RSoulatIOHK ... and others

**Comment by RSoulatIOHK** [comment]
Useful links:

- https://github.com/Anastasia-Labs/design-patterns 
- https://plutonomicon.github.io/plutonomicon/vulnerabilities 
- https://www.mlabs.city/blog/common-plutus-security-vulnerabilities
- https://aiken-lang.org/fundamentals/common-design-patterns

Discussions:

A lot of things will be dependant on the code generation => Do we need to take into account the compiler version?

Could we implement some design patterns as rules? See useful links for Anastasia and Aiken lists
- Minting policy 
   - If we look at the script context and it's minting, we want to check that the asset name is checked explicitely

- Useful for information the users about suboptimal constructions
   - Could be solved by a new version of the compiler
   - Would require a close collaboration with the Core team to know in advance what will be fixed
   - Can we detect which version of the compiler ? Form cabal for sure, but what if there is no cabal file?
       - Which behaviour to adopt if we can't know?
 **- Program to collect Antipatterns?
   -  Twitter post?** 
      - Should we create a Plutus HA Twitter handle? Link to the newly created by Marshall?
      - Twitter space to discuss Plutus HA things?
      - Build a twitter post, tag a few developers and see if spreads
      - Contact developers beforehand that we know of so that they can think of something and then get the ball rolling.
   **- Working group**
       - Item on the agenda for next week?
       - Should we try to find one, implement it so that it is a bit more impactful? 

Ali suggested having information about not really bugs but common mistakes that people make
- @Ali-Hill can you reexplain it, I forgot to take notes

**Reviewing audit reports && bug reports**
- Minswap LP token bug <- Minting policy 

Should the static analyzer look at the off-chain code and have custom rules that are not just Haskell rules?

From a previous with JFE, integrate Abstract Interpretation in the tool?
- Might be A LOT of work

### Actions:
- [ ] Discuss about this tweet for the initiative to collect rules and antipatterns
- [ ] List some audit reports, @Riley-Kilgore has one, @RSoulatIOHK also has one => Let's create a thread on slack to drop them
- [x] Ask Stefano and Marshall to promote the WG for next week. 
- [ ]
